version: '3.8'
services:
    nestjs_server:
        image: node:20.11.1
        restart: always
        container_name: nestjs_server
        network_mode: host
        # ports:
        #     - 3003:3003
        volumes:
            - ../:/usr/src/app
        command:
            - sh
            - -c
            - |
                cd /usr/src/app
                [ ! -d "/usr/src/app/node_modules" ] && npm config set strict-ssl false && npm install --omit=dev --registry=https://registry.npm.taobao.org
                cd /usr/src/app/src/db/prisma/
                npx prisma generate
                cd /usr/src/app
                npm run start:dev
